### PR TITLE
3-0-stable Volume Price Model

### PR DESCRIPTION
**Pull request by jspizziri**
In favor of: https://github.com/spree-contrib/spree_volume_pricing/pull/73

### CODE REVIEW

**Comment by futhr** [comment]
Hi @jspizziri, its looking good! I'm working on it here: https://github.com/futhr/spree_volume_pricing/commit/08e0236449ec3e64ba9d5748d7cb0ac0c0f52425 where I took the liberty to rebase your work commits into a single "readable" commit. It pushed down the spec coverage from ~90% to ~80% so I need to write some new specs for it etc. It has major changes so it will be for `master` branch to begin with. If you (or anyone) are in a hurry to get this merged you may always cherry-pick it and fix the remaining parts (specs, i18n, layout tweaks, validation and documentation).

**Comment by jspizziri** [comment]
@futhr, Thanks! I really appreciate all your help with this! That makes sense about putting it in master first.

Theres currently a discussion going on about this PR in another one that I don't know if you've seen yet. https://github.com/spree-contrib/spree_volume_pricing/pull/75

Thanks again! If I get any time in the next week I'll try and do some more work on it.

**Comment by futhr** [comment]
@jspizziri Yes, due to #75 this probably gonna be on hold for a while until we decided, I actually like the role model pattern better in the other commit but like the suggested way to manage records.

**Comment by jspizziri** [comment]
@futhr I think we're at a point in the decision making process where we need a contributor to weigh in and be the deciding factor so we can get moving on this.

The two philosophies are this (I'll try and be as unbiased as possible here but @juancroca should weigh in and present his side):

1. Apply the role relationship directly to the VolumePrice
    1. Pros
        1. Doesn't affect the data Model as much (easier migrations)
        2. May perhaps be slightly less hassle to add pricing
    2. Cons
        1. IMHO, less robust than the other solution
2. Have a VolumePriceModel (VPM) which VolumePrices are associated with and associate the VPM with a variant
    1. Pros
        1. IMHO, more robust in that the prices can be leveraged & manipulated in a much more abstract and powerful way.
    2. Cons
        1. Fairly significant change to the Data Model
        2. Perhaps slightly more complex to add to variants as you have to create a VPM first
            1. Its important for me to note that I propose solving this complexity by allowing VPM's to be created in the same interface that you would add them to a variant.

Both solutions propose that if a VolumePriceModel, or set of VolumePrices are added to the Master Variant of a product, and a configuration option is selected, then those prices apply to every variant of that product.

**Comment by juancroca** [comment]
@jspizziri I just made a new pull request trying to merge both option please check out #83. Let me know if this could work for you.

**Comment by jspizziri** [comment]
@futhr , @juancroca's newest proposal accomplishes both the things trying to be accomplished in the prior 2 PR's.

Will you take a look at it and give your thoughts?

**Pull request closed without merging**
