### PR TITLE
make sure that vprice exists

### PR DESCRIPTION
**Pull request by PatLeb**

### CODE REVIEW

**Comment by jspizziri** [comment]
The specs are failing.

**Comment by PatLeb** [comment]
Yep, sorry, I don't have any time to find out why, but I highly doubt that my commit is the root cause since this plugin runs well within our app.

**Comment by jspizziri** [comment]
The master build is currently passing, the only difference in that build is your code, so it has to be your commit.

**Comment by PatLeb** [comment]
I really don't have time for this, but I assure you that if you run your spec locally with the current master branch, then you'll get the same errors. I suspect that there is a core maintainer who have been committing some changes (either in the code or in the specs) without doing a pull request first.

**Comment by jspizziri** [comment]
Sorry, I appreciate you taking the time to submit a PR, and respect that you don't have time to fix it, however we can't merge this in unless the build passes.

As you can see here https://travis-ci.org/spree-contrib/spree_volume_pricing/builds/78251992, the most recent commit on master is passing in Travis.

**Comment by PatLeb** [comment]
No problem about closing the PR, but I suggest that you restart your build in travis.

**Pull request closed without merging**
