### PR TITLE
Templates with Volume Price Model

### PR DESCRIPTION
**Pull request by juancroca**
This is what I would considered a happy marriage between #77 and #76. You still have the ability to create volume prices directly in a variant but are also able te set a volume price model to a variant so it can be used as a template.

### CODE REVIEW

**Comment by jspizziri** [comment]
@juancroca, this looks good to me. I think ultimately the marriage of these two PR's is going to be good for the store admin.

**Comment by juancroca** [comment]
@futhr @JDutil is there any estimation when this could be merged?

**Comment by jspizziri** [comment]
+1, it would be awesome to get at least one of these PR's merged.

**Comment by JDutil** [comment]
@jspizziri do you not have commit access to this repo?

**Comment by JDutil** [comment]
Merged to 3-0-stable and master.  I'm not really following this project much anymore so if you guys would like access to maintain it let me know.

**Comment by jspizziri** [comment]
@JDutil, I don't have access to this repo, I'd be interested in being added if @juancroca wants to tag team support with me, but I don't know if I could be responsive enough by myself.

**Comment by JDutil** [comment]
@jspizziri don't expect you to be responsive to everything yourself just take care of whatever is relevant to the work your doing. Basically just need people to take care of what they can when they can, but remain considerate of not making breaking changes to stable branches / specs.  I'm removing myself from contributing to many projects including this one because I don't have the time or use anymore now that I'm no longer developing my old Spree website.

**Comment by juancroca** [comment]
@JDutil sure I wouldn't mind showing some love to this project :P

**Comment by JDutil** [comment]
@juancroca you should received an invite if you haven't already.

**Pull request closed without merging**
