### PR TITLE
add role to volume_price

### PR DESCRIPTION
**Pull request by juancroca**
Added the ability to set a role to a volume_price, works if no role is passed also.

### CODE REVIEW

**Comment by jspizziri** [comment]
@juancroca, is this something that's intended for the volume pricing model update?

**Comment by juancroca** [comment]
@jspizziri i found that the volume price model was to bothersome, I get that it works nice as a template but I find that every time we want to create a volume price we need to create a volume price model its a bit to much. Its just a simpler way to implement roles. Also this way you can have different roles still working with a volume price not just only wholesale.

**Comment by JDutil** [comment]
Yea I'm thinking this is a simpler implementation, and will be easier for people to migrate too when upgrading from older versions. Is this lacking anything @jspizziri that you were hoping to get out of your implementation?

**Comment by jspizziri** [comment]
@JDutil and @juancroca, my concerns are that when you're dealing with a large set of products, you don't want to create a new set of volume prices for each product. Additionally, when you have more complex pricing structures it becomes more and more unmanageable. This is especially the case if business requirements necessitate pricing changes. If we don't use a model, and then there is a potential that extensive updates are going to have to be performed by administrators, which leaves room for error.

**Comment by juancroca** [comment]
@jspizziri i get what ur saying but the volume me price model solution only really works if you are only doing percentages because if you want to set a default price or the dollar subtraction method you would need a new volume price model for each product again because each product has a different price. But what I can get from your approach is that we need some type of templates and I would agree but I feel you should force them to use a template. Also I would suggest (and will make that pull request once this is settled) that if we set a volume price on the master variant this one should be used if the other variants dont have a volume price. Maybe thoose two additions would avoid the problem you stated.

**Comment by juancroca** [comment]
@JDutil so what is ur decision regarding roles?

**Comment by jspizziri** [comment]
@juancroca, each product doesn't necessarily have a different price. For instance, my client has a situation where groups of products cost a similar amount.

But I see what you're saying. Perhaps then the best solution is actually a both and. You can specify a model, or a volume price directly on a product.

**Comment by QuintinAdam** [comment]
Just to chime in @jspizziri version is working really good for me. +1 for combining both versions.

**Comment by jspizziri** [comment]
Also, another compromise would be to allow for the creation of Volume Pricing Models at the product level, so that the Volume Prices could be created more quickly.

**Comment by juancroca** [comment]
@jspizziri yeah I would like to add the behavior that if you specify some volume price on the master variant this will be picked up by any variant without a volume price. Will this be good enough for you or you would still like to see some templating solution for the volume prices?

**Comment by jspizziri** [comment]
@juancroca , Actually I totally agree, I was actually intending to have that functionality if you look at my original issue, but I didn't want to get too carried away with changes :). I think it might be good if it were a flag on the relationship between product->pricing_model, so if you specify a model on a master variant, and check `apply_to_all` then it would be applied accordingly. (Or something like this.)

**Comment by JDutil** [comment]
@juancroca I don't really have a strong opinion either way here. 

I no longer use this extension so I'd tend to side with the simpler approach for dealing with roles rather than introducing new models, and drastic changes that may not be easy for people upgrading from older versions.  So personally I'd prefer this PR over the other since it's simpler, and less likely to cause people problems.

That being said I'm not the one using this extension anymore so it's really up to you guys to decide what you want as your going to be the ones using it going forward.

**Comment by juancroca** [comment]
@jspizziri this is what I had in mind juancroca@0f06f47950efabe6b2e679e0420384d0cadcbcb4, take a look over it and tell me if this would be enough for a "templating" solution. This would set the master variant to be the default for all empty volume_prices in the variants of that product. I left the spree config to false so it is backward compatible(you can change the use_master_variant_volume_pricing spree config in the spree.rb to true).  If this works I would like to make a new pull request @JDutil feel free to comment about this solution as well.

**Comment by jspizziri** [comment]
@juancroca, I'm a little wary of just having it as a configuration option which is applied globally, but it will probably work. If people have a problem with it it may have to change to accommodate a product by product scenario.

**Comment by juancroca** [comment]
@jspizziri I'm not sure if I may be understanding you correctly but is your concern that if the variable use_master_variant_volume_pricing is set to true then by default the price would be the one defined by the master variant instead of the product specific variant? If that is your concern then we are ok since this doesn't happen. It only takes the price of the master variant in the case the specific variant has no volume pricing defined, the master variant does and use_master_variant_volume_pricing is set to true. If any of this conditions fails we try to get the price from the product specific variant. @JDutil would like you to weigh in on this should I make the new pull request with this changes? I'm currently on hold to add this functionality to an app ready to be deployed and I'm willing to help out to move this as fast as possible.

**Comment by jspizziri** [comment]
@juancroca, no, my concern is that if someone has two products with different use cases on their store.

Product #1 could have 5 variants but only have volume prices for the master variant (in this case volume pricing shouldn't be applied to all variants)

Product #2 would have 5 variants with a volume pricing on the master with the desired behavior that it be applied to all variants of the product.

**Comment by juancroca** [comment]
@jspizziri but I don't understand the first scenario you describe why would you add a volume price to the master variant if you don't want it to be applied to the variants, once you have variants you can't buy a product with the master variant this is only used when its the only variant available for the product. So for product 1 if you have 5 variants and you don't want them to have the volume price of the master variant just don't add a master volume price or if you want a master volume price as default and a different one for a specific variant just override it in that variant.

**Comment by jspizziri** [comment]
That's a very good point! I didn't realize that. In that case then I think that solution for applying volume prices to all variants is a good one.

**Comment by juancroca** [comment]
Im closing this pull request in favor of #77 with the added "templating" solution with the master variant.

**Comment by jspizziri** [comment]
@juancroca 

I think we still misunderstand each other. I'm still in favor of having a "Volume Pricing Model" with associated Volume Prices. I only mean that I think that this should be done in conjunction with it.

**Comment by juancroca** [comment]
@jspizziri I do understand but I still think a Volume Pricing Model(VPM) is a bit of an overkill since I stated before I don't think we should have the need to force the creation a new VPM record when I just want to add one Volume Price(VP) for one variant because then we would end up creating the same amounts of VPM as VP. That is why I would keep the ownership of the VP to the variant. I feel #77 is a simpler approach but I do agree with you that a fancier templating solution that doesn't force a VPM would be nice.

**Comment by jspizziri** [comment]
@juancroca, Please check out this thread: https://github.com/spree-contrib/spree_volume_pricing/pull/76#issuecomment-111175933

**Pull request closed without merging**
